# Generated by Django 6.0.1 on 2026-01-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("quantite", models.PositiveIntegerField(default=0)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("categorie", models.CharField(max_length=50)),
                ("seuil_alerte", models.PositiveIntegerField(default=5)),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["nom"],
            },
        ),
    ]
